---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: staging
spec:
  secretRef:
    name: github
  image: ghcr.io/vdksystem/common-app
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: staging
spec:
  imageRepositoryRef:
    name: staging
  filterTags:
    pattern: '^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-rc(?:\.[0-9]+))$'
  policy:
    semver:
      range: '^0.x-0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: staging
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      messageTemplate: |
        STAGE automated image update
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
