apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - https://github.com/vdksystem/flux-gha-app//deploy?timeout=120
images:
  - name: ghcr.io/vdksystem/flux-gha-app
    newTag: sha-d6003f3593687896eba1b883a4d474f5788eb738
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: github
